import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ width: "100vw" }}>
      <head>
        <meta http-equiv="Pragma" content="no-cache" />
        <meta
          http-equiv="cache-control"
          content="no-cache, no-store, must-revalidate"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
